#cloud-config

#fs-4d559484.efs.eu-west-1.amazonaws.com:/	/webserver	nfs	nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0

coreos:
  units:
    - name: rpc-statd.service
      command: start
      enable: true
    - name: webserver.mount
      command: start
      content: |
        [Mount]
        What=fs-4d559484.efs.eu-west-1.amazonaws.com:/
        Where=/webserver
        Type=nfs
        Options=nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,nofail
        [Install]
        WantedBy=multi-user.target
